# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app code and model
COPY app .

# Expose port
EXPOSE 5000

# Run the app
CMD ["python", "app.py"]